### ISSUE TITLE
Exceptions related to empty configuration files

### ISSUE THREAD

**Issue by swltr** [gestalt-config/gestalt#117]
It seems there is an issue when an empty file is encountered. This is with 0.23.2:

```
[20231010-13:37:48-679] SEVERE  main                 o.o.kernel.RunKernel.main()                            : Error creating the configuration provider: 
org.github.gestalt.config.exceptions.GestaltConfigurationException: Failed to load configs from source: File source: C:\Repos\opentcs\openTCS-Kernel\build\install\openTCS-Kernel\.\config\opentcs-kernel.properties
 - level: ERROR, message: Empty or null token provided while building the config node
	at org.github.gestalt.config.GestaltCore.validateLoadResultsForErrors(GestaltCore.java:210)
	at org.github.gestalt.config.GestaltCore.loadConfigs(GestaltCore.java:126)
	at org.github.gestalt.config.GestaltCache.loadConfigs(GestaltCache.java:38)
	at org.opentcs.configuration.gestalt.GestaltConfigurationBindingProvider.<init>(GestaltConfigurationBindingProvider.java:74)
	at org.opentcs.kernel.RunKernel.configurationBindingProvider(RunKernel.java:127)
	at org.opentcs.kernel.RunKernel.customConfigurationModule(RunKernel.java:86)
	at org.opentcs.kernel.RunKernel.main(RunKernel.java:63)
```

and, when reloading:

```
[20231010-13:42:36-343] SEVERE  Timer-1              o.g.g.c.reload.TimedConfigReloadStrategy$1.run()       : Exception reloading source File source: C:\Repos\opentcs\openTCS-Kernel\build\install\openTCS-Kernel\.\config\opentcs-kernel.properties, exception org.github.gestalt.config.exceptions.GestaltException
org.github.gestalt.config.exceptions.GestaltException
	at org.github.gestalt.config.reload.ConfigReloadStrategy.reload(ConfigReloadStrategy.java:71)
	at org.github.gestalt.config.reload.TimedConfigReloadStrategy$1.run(TimedConfigReloadStrategy.java:38)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

In this case, the file `opentcs-kernel.properties` is empty. (It is supposed to only contain overrides for defaults set in other files.)

**Comment by credmond-git** [comment]
Thanks i never considered an empty source file, i am sure i can add some special case handling of empty sources.

**Comment by credmond-git** [comment]
Try release v0.23.3 https://github.com/gestalt-config/gestalt/releases/tag/v0.23.3

**Comment by swltr** [comment]
@credmond-git That seems to have fixed it, thank you! :+1:
